### ISSUE TITLE
Implement re-roll after two duplicate blocks in a row

### ISSUE THREAD

**Issue by TheFrostlixen** [matthewjberger/Iceberg3D#1]
Implement a re-roll (similar to the blue 4x1 block) when the same type of block appears two or more times. This may or may not also include the blue blocks, resulting in a double re-roll for blues (it is unclear how this would affect potential balance). This change will reduce the frequency of large numbers of duplicate blocks.

**Comment by matthewjberger** [comment]
Wrong project.
