### ISSUE TITLE
Enter post-game score on High Score screen

### ISSUE THREAD

**Issue by TheFrostlixen** [matthewjberger/Iceberg3D#2]
Change the post-game score entering system to display the high scores list, with the current game's score sorted in place and the name with a blank line and blinking cursor. This way you will enter your score on the High Scores screen, and be able to see where your score fits in with this others.

**Comment by matthewjberger** [comment]
Wrong project.

**Comment by matthewjberger** [comment]
Issue moved to [matthewjberger/Tetris366--complete-- #4](https://github.com/matthewjberger/Tetris366--complete--/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
